//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Tms.Domain.Entity.ToolManage
{
    public  class CheckEntity 
    {
        public int T_CheckType { get; set; }
        public int T_IsChecked { get; set; }
        public int Id { get; set; }
        public string T_Id { get; set; }
        public string T_CheckPerson { get; set; }
        public string T_CheckDetails { get; set; }
        public string T_DepartmentId { get; set; }
        public string T_EditedPerson { get; set; }
        public string T_Description { get; set; }
        
        public string T_CheckedImg { get; set; }

        public Nullable<System.DateTime> T_LastCheckTime { get; set; }
        public Nullable<System.DateTime> T_ThisCheckTime { get; set; }
        public Nullable<System.DateTime> T_CreateTime { get; set; }
        
    }
}
