//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Tms.Domain.Entity.ToolManage
{


    public  class CheckEntity : IEntity<CheckEntity>
    {
        public string T_Id { get; set; }
        public string T_One { get; set; }
        public string T_Two { get; set; }
        public string T_Three { get; set; }
        public string T_Four { get; set; }
        public string T_Five { get; set; }
        public string T_Six { get; set; }
        public string T_Seven { get; set; }
        public string T_Eight { get; set; }
        public Nullable<System.DateTime> T_CheckTime { get; set; }
        public string T_CheckerId { get; set; }
        public Nullable<System.DateTime> T_Creator { get; set; }
        public string T_DepartmentId { get; set; }
    }
}
