//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Tms.Domain.Entity.ToolManage
{
    public  class CheckViewEntity
    {
        public int T_CheckType { get; set; }
        public int T_IsChecked { get; set; }
        public int Id { get; set; }
        public string T_Id { get; set; }
        public string T_CheckPerson { get; set; }
        public string T_CheckDetails { get; set; }
        public string T_DepartmentId { get; set; }
        public string T_EditedPerson { get; set; }
        public string T_Description { get; set; }
        public Nullable<System.DateTime> T_LastCheckTime { get; set; }
        public Nullable<System.DateTime> T_ThisCheckTime { get; set; }
        public Nullable<System.DateTime> T_CreateTime { get; set; }

        ///////////////////////////////////////////////////////
        public string T_Code { get; set; }
        public int T_SeqId { get; set; }
        public string T_ToolType { get; set; }
        public int T_ToolStatus { get; set; }
        public string T_Img { get; set; }
        public string T_Hander { get; set; }
        public string T_RecPersonId { get; set; }
        public string T_Location { get; set; }
        public Nullable<int> T_UsedCount { get; set; }
        public Nullable<int> T_UsedTime { get; set; }
        public Nullable<System.DateTime> T_RegDate { get; set; }
        public Nullable<int> T_RepairedCounts { get; set; }
        public Nullable<int> T_DefineId { get; set; }
        public Nullable<System.DateTime> T_ToolProductedDate { get; set; }
        public string T_Name { get; set; }
        public string T_Family { get; set; }
        public string T_Model { get; set; }
        public string T_PartNo { get; set; }
        public int T_PmPeriod { get; set; }


    }
}
