//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Tms.Domain.Entity.ToolManage
{
   
  
    public class CodeSeqIdEntity 
    {
        public int T_SeqId { get; set; }
        public int T_Occupy { get; set; }
        public string T_Code { get; set; }
        public int T_Id { get; set; }
        public string T_DepartmentId { get; set; }
    }
}
