//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Tms.Domain.Entity.ToolManage
{


    public  class DefineEntity : IEntity<DefineEntity>
    {
        public int T_Id { get; set; }
        public string T_Code { get; set; }
        public string T_Name { get; set; }
        public string T_FamilyId { get; set; }
        public string T_Model { get; set; }
        public string T_PartNo { get; set; }
        public Nullable<int> T_Upl { get; set; }
        public string T_UsedFor { get; set; }
        public Nullable<int> T_PmPeriod { get; set; }
        public string T_OwnerId { get; set; }
        public string T_RecPerson { get; set; }
        public string T_OwnerName { get; set; }
        public string T_DepartmentId { get; set; }
        public string T_Editer { get; set; }
        public Nullable<System.DateTime> T_EditedTime { get; set; }
        public Nullable<System.DateTime> T_CreatorTime { get; set; }
    }
}
