// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Tms_FrameworkML.Model
{
    public class ModelInput
    {
        [ColumnName("UseTime"), LoadColumn(0)]
        public float UseTime { get; set; }


        [ColumnName("RepairCounts"), LoadColumn(1)]
        public float RepairCounts { get; set; }


        [ColumnName("Result"), LoadColumn(2)]
        public bool Result { get; set; }


    }
}
